language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

script:
  - ./gradlew clean test jacoco sonarqube -Dsonar.login=${SONAR_TOKEN}
  - ./travis.sh
after_success: test "${TRAVIS_PULL_REQUEST}" == "false" && test "${TRAVIS_JDK_VERSION}" == "oraclejdk7" && ./gradlew uploadArchives

